# Generated by Django 5.2.12 on 2026-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("strictness", models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="attendance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(default="MCA", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="canteen_debt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="crush_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="fashion_level",
            field=models.IntegerField(default=0),
        ),
    ]
